# Generated by Django 3.1 on 2020-11-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_name',
            field=models.CharField(default='my first blog', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_text',
            field=models.CharField(max_length=9999),
        ),
    ]
