# Generated by Django 3.1 on 2020-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20201114_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='blog_text',
            field=models.CharField(default='hello world', max_length=9999),
        ),
        migrations.AlterField(
            model_name='index',
            name='blog_name',
            field=models.CharField(default='test blog', max_length=200),
        ),
    ]
