# Generated by Django 3.1 on 2020-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20201115_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_pass',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='first_auth_date',
            field=models.DateTimeField(auto_now_add=True, default='s'),
            preserve_default=False,
        ),
    ]
