# Generated by Django 3.1 on 2020-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20201129_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_auth_date',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
