# Generated by Django 3.1 on 2020-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20201129_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_pass',
            field=models.CharField(max_length=200),
        ),
    ]
