# Generated by Django 3.1 on 2020-12-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_author'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
